### ISSUE TITLE
Allow saving custom configuration on RetroArch

### ISSUE THREAD

**Issue by mgoulartBR** [digitalLumberjack/retrobox-emulationstation#8]
I tried to save some config modifications on RetroArch but always that I leave RetroArch the default configuration is loaded.

**Comment by digitalLumberjack** [comment]
The retroarch config file was overwritten each time a game was launched. It was for security purpose.

I changed the configuration system in the last commit, so if you change settings in retroarch menu, and if you set "Automatic Config Save" to ON in "General Settings", your modifications will now be saved.
